#!/bin/bash
# Instructions to update KERN1 Invoice OCR to latest version

echo "KERN1 Invoice OCR - Git Update Instructions"
echo "==========================================="
echo ""
echo "Run these commands in Terminal:"
echo ""
echo "1. Navigate to your project folder:"
echo "   cd ~/Documents/ocr/ocr_expenses"
echo ""
echo "2. Pull latest changes:"
echo "   git pull origin claude/invoice-ocr-excel-export-011CUqTK38eakRm21Z5Nb2tL"
echo ""
echo "3. If you get merge conflicts or errors:"
echo "   git fetch origin"
echo "   git reset --hard origin/claude/invoice-ocr-excel-export-011CUqTK38eakRm21Z5Nb2tL"
echo ""
echo "4. Delete old virtual environment (recommended):"
echo "   rm -rf venv"
echo ""
echo "5. Run the launcher to reinstall everything:"
echo "   Double-click KERN1_Invoice_OCR.command"
echo ""
